# Generated by Django 4.2 on 2025-02-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_concert_name_alter_concert_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.URLField(default='https://www.bing.com/th?id=OIP.Gtl8XmpSOEf1zXrgaSwW9AHaE8&w=309&h=211&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2', max_length=500),
        ),
    ]
