# Generated by Django 4.2 on 2025-01-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tickets_booked',
            field=models.PositiveIntegerField(),
        ),
    ]
