# Generated by Django 4.2 on 2025-03-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_tickets_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.PositiveBigIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
